import type { NextPage } from "next";
import Head from "next/head";

import { ItemsList } from "../components/ItemsList";
import { PostsHeader } from "../components/PostsHeader";

import styles from "./Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostsHeader title="Últimas notícias" results={3} />
      <main className={styles.main}>
        <ItemsList posts={[]} />
      </main>
    </div>
  );
};

export default Home;
